export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "NL", name: "Netherlands" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "ZA", name: "South Africa" },
  { code: "EG", name: "Egypt" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "MA", name: "Morocco" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Philippines" },
  { code: "ID", name: "Indonesia" },
  { code: "MY", name: "Malaysia" },
  { code: "SG", name: "Singapore" },
  { code: "NZ", name: "New Zealand" },
];

export const SERVICES = [
  { value: "stuttering", label: "Stuttering" },
  { value: "apraxia", label: "Apraxia" },
  { value: "voice", label: "Voice Therapy" },
  { value: "language", label: "Language Therapy" },
  { value: "swallowing", label: "Swallowing" },
  { value: "cognitive", label: "Cognitive" },
  { value: "articulation", label: "Articulation" },
  { value: "fluency", label: "Fluency" },
];

export const COST_LEVELS = [
  { value: "free", label: "Free", color: "green" },
  { value: "low-cost", label: "Low Cost", color: "orange" },
  { value: "market-rate", label: "Market Rate", color: "blue" },
];
